# Generated by Django 5.2.8 on 2025-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default='Restaurant Co.', max_length=100)),
                ('password', models.CharField(max_length=600)),
                ('email', models.EmailField(default='example@example.com', max_length=100, unique=True)),
            ],
        ),
    ]
