# Generated by Django 5.2.8 on 2025-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='organization',
            field=models.CharField(default='Bankers Bank', max_length=100),
        ),
    ]
