# Generated by Django 5.2.8 on 2025-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_email_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='organization',
            field=models.CharField(default='Restaurant Co.', max_length=100),
        ),
    ]
