# Generated by Django 5.2.8 on 2025-11-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_email_alter_restaurant_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
