# Generated by Django 5.2.8 on 2025-11-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='salt',
            field=models.CharField(default='RestaurantID', editable=False, max_length=100),
        ),
    ]
