# Generated by Django 5.2.8 on 2025-11-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='salt',
        ),
    ]
