# Generated by Django 5.2.8 on 2025-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federal',
            name='organization',
            field=models.CharField(default='Department of Human Intelligence', max_length=100),
        ),
    ]
